# Generated by Django 3.0.2 on 2020-01-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voted_product',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
