# Generated by Django 3.0.2 on 2020-01-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200130_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voted_product',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
    ]
