# Generated by Django 3.0.2 on 2020-01-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200130_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='voted_product',
            name='vote_number',
            field=models.CharField(default='voted', max_length=20),
        ),
    ]
