# Generated by Django 3.0.2 on 2020-01-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200131_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voted_product',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voted_product',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
