# Generated by Django 3.0.2 on 2020-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vote_string',
            field=models.CharField(max_length=25),
        ),
    ]
