# Generated by Django 3.0.2 on 2020-01-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200128_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='vote_string',
        ),
    ]
